###############################################################################
# Created by write_sdc
# Fri Apr 21 16:46:48 2023
###############################################################################
current_design tt2_tholin_namebadge
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 100.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_in[0]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_in[1]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_in[2]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[10]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[11]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[12]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[13]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[14]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[15]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[16]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[17]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[18]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[19]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[20]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[21]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[22]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[23]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[24]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[25]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[26]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[8]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_oeb[9]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_out[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_out[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_out[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_out[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_out[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_out[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_out[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {io_out[7]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {io_oeb[26]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[25]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[24]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[23]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[22]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[21]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[20]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[19]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[18]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[17]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[16]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[15]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[14]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[13]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[12]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[11]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[10]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[9]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[8]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[7]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[6]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[5]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[4]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[3]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[2]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[1]}]
set_load -pin_load 0.0334 [get_ports {io_oeb[0]}]
set_load -pin_load 0.0334 [get_ports {io_out[7]}]
set_load -pin_load 0.0334 [get_ports {io_out[6]}]
set_load -pin_load 0.0334 [get_ports {io_out[5]}]
set_load -pin_load 0.0334 [get_ports {io_out[4]}]
set_load -pin_load 0.0334 [get_ports {io_out[3]}]
set_load -pin_load 0.0334 [get_ports {io_out[2]}]
set_load -pin_load 0.0334 [get_ports {io_out[1]}]
set_load -pin_load 0.0334 [get_ports {io_out[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {io_in[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
