name: Tests (RTL)

on: [ push, workflow_dispatch ]
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      OPENLANE_ROOT: /home/runner/openlane
      PDK_ROOT: /home/runner/pdk
      PDK: sky130B
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install PDK
        run: make setup

      - name: Run all tests
        run: |
          make verify | tee test.log
          ! grep failed test.log
          ! grep failure test.log
